In [5]:
import numpy as np
x = np.array([1,2,3])
x.__class__

numpy.ndarray

In [4]:
x.shape

(3,)

In [6]:
x.ndim

1

In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [11]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

h = np.dot(x, W1) + b1
a = sigmoid(h)
s = np.dot(a, W2) + b2
print(s)

[[ 2.54758125 -0.43507421 -0.45772271]
 [ 1.96477294  0.5598872  -0.96995466]
 [ 2.36714469  0.06529342 -0.65088121]
 [ 2.52163627 -0.44964729 -0.42089238]
 [ 2.26884107  0.27126063 -0.7953458 ]
 [ 2.26234569 -0.14661349 -0.48464328]
 [ 1.92741156 -1.46748672  0.46322549]
 [ 1.89893434 -1.25901118  0.370214  ]
 [ 2.18737016 -0.30921791 -0.35240243]
 [ 2.64843111  0.54170346 -0.95944429]]


In [13]:
class Sigmoid:
    def __init__(self):
        self.params = []
        
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [1]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
    
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

In [ ]:
# jupyter lab chap1.ipynb